services:
    gitlab:
        image: gitlab/gitlab-ce:latest
        container_name: gitlab
        hostname: localhost
        environment:
            GITLAB_OMNIBUS_CONFIG: |
                external_url 'http://localhost'
        ports:
            - '80:80'
            - '443:443'
            - '22:22'
        volumes:
            - gitlab-config:/etc/gitlab
            - gitlab-logs:/var/log/gitlab
            - gitlab-data:/var/opt/gitlab
        shm_size: 256m

volumes:
    gitlab-config:
    gitlab-logs:
    gitlab-data:
